---
- hosts: network
  gather_facts: true
  tasks:
  - name: Network Resource Manager
    ansible.builtin.include_role:
      name: network.base.resource_manager
    vars:
      operation: configure
      ansible_network_os: cisco.ios.ios
      resource: interfaces
      config:
        - enabled: true
          name: GigabitEthernet1
          description: "Configured with Ansible Network Validated Content Configure Action"
        - enabled: true
          name: VirtualPortGroup0
      state: merged
