---
- hosts: network
  gather_facts: true
  tasks:
    - name: Network Resource Manager
      ansible.builtin.include_role:
        name: network.base.resource_manager
      vars:
        operation: deploy
        ansible_network_os: cisco.ios.ios
        resources:
          - 'interfaces'
        data_store:
          local: '/home/rhel/network_inventory'
