---
- hosts: network
  gather_facts: true
  tasks:
    - name: Network Resource Manager
      ansible.builtin.include_role:
        name: network.base.resource_manager
      vars:
        ansible_network_os: cisco.ios.ios
        operation: gather
        resources:
          - 'interfaces'
          - 'l2_interfaces'
          - 'l3_interfaces'
