---
- hosts: network
  gather_facts: true
  tasks:
    - name: Network Resource Manager
      ansible.builtin.include_role:
        name: network.base.resource_manager
      vars:
        ansible_network_os: cisco.ios.ios
        operation: gather
        resources:
          - 'interfaces'
          - 'l2_interfaces'
          - 'l3_interfaces'
       ignore_errors: true
    
    - name: Read the content of the file
      ansible.builtin.slurp:
        src: "/etc/ansible_rh.log"
      register: file_content

    - name: Display the content of the file
      ansible.builtin.debug:
        msg: "{{ file_content.content | b64decode }}"
