---
- hosts: network
  gather_facts: true
  tasks:
  - name: Network Resource Manager
    ansible.builtin.include_role:
      name: network.base.resource_manager
    vars:
      action: list
      ansible_network_os: cisco.ios.ios
 
