- name: Create Network Backup Play
  hosts: network
  tasks:
    - name: Create Network Backup
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: backup
        ansible_network_os: cisco.ios.ios 
        data_store:
          scm:
            origin:
              # url: "https://github.com/rohitthakur2590/network_automation_backups"
              url: "https://podman-3000-4ogb3mexnv5h.env.play.instruqt.com:3000/student/demo_network_backups.git"
              # token: "{{ VALIDATED_RO_KEY }}"
