- name: Create Network Backup Play
  hosts: network
  tasks:
    - name: Create Network Backup
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: backup
        ansible_network_os: cisco.ios.ios 
        data_store:
          scm:
            origin:
              user:
                name: "student"
                email: "student@example.com" 
              url: "https://podman-3000-px8kxjhraydy.env.play.instruqt.com:3000/student/network_backups.git"   
              # url: "https://github.com/rohitthakur2590/network_automation_backups"
              # token: "{{ VALIDATED_RO_KEY }}"
