---
- name: Detect Network Backup Diff
  hosts: network_diff
  gather_facts: true
  tasks:
    - name: Detect Diff
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: detect
        ansible_network_os: cisco.ios.ios 
        data_store:
          scm:
            origin:
              url: "https://github.com/rohitthakur2590/network_automation_backups"
